---
jobs:
  include:
    - name: High Sierra
      os: osx
      osx_image: xcode10.1
      language: minimal

before_install:
  # Install pip
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H /usr/bin/python
  - which pip
  - pip --version

  # Setup virtualenv
  - sudo -H pip install -U virtualenv
  - virtualenv --version
  - virtualenv .venv
  - source .venv/bin/activate

install:
  # Dependencies
  - >-
    pip install "ansible${ANSIBLE_VERSION}"
    ansible-lint
    testinfra
    yamllint
    --ignore-installed six

  # Check versions
  - ansible --version
  - ansible-lint --version
  - py.test --version
  - yamllint --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\ninventory = tests/inventory' > ansible.cfg

script:
  # Lint all YAML files.
  - yamllint .
  # Lint test playbook
  - ansible-lint tests/playbook.yml

  # Check the role/playbook's syntax.
  - ansible-playbook tests/playbook.yml -i tests/inventory --syntax-check

  # Test role/playbook
  - ansible-playbook tests/playbook.yml -i tests/inventory
  - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  - py.test -v tests/role.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
