---
jobs:
  include:
    - name: High Sierra
      os: osx
      osx_image: xcode10.1
      language: minimal

before_install:
  # Install pip
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H /usr/bin/python
  - which pip
  - pip --version

install:
  # Dependencies
  - >-
    pip3 install "ansible${ANSIBLE_VERSION}"
    ansible-lint
    yamllint

  # Check ansible version
  - ansible --version
  - ansible-lint --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\ninventory = tests/inventory' > ansible.cfg

script:
  # Lint the role.
  - ansible-lint tests/playbook.yml

  # Check the role/playbook's syntax.
  - ansible-playbook tests/playbook.yml -i tests/inventory --syntax-check

  # Test role/playbook
  - ansible-playbook tests/playbook.yml -i tests/inventory
  - export PATH=${PATH}:/Users/travis/Library/Python/3.7/bin

  # Symbolik link to python3 -> python
  - ls -l /usr/local/bin/python
  - ln -s /usr/local/bin/python3 /usr/local/bin/python
  - ls -l /usr/local/bin/python

  # Lint all YAML files.
  - yamllint --version
  - yamllint .

  - which python
  - python --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
